export const strings = {
  title: "لیست سوالات",
  newQuestion: "سوال جدید",
  createNewQuestion: "ایجاد سوال جدید",
  subject: "موضوع",
  subjectPlaceholder: "موضوع مرتبط با سوال خود را در این قسمت بنویسید",
  questionTextTitle: "متن سوال",
  questionTextPlaceholder: "متن سوال خود را در این قسمت بنویسید",
  cancel: "انصراف",
  createQuestion: "ایجاد سوال",
  timeTitle: "ساعت",
  dateTitle: "تاریخ",
  moreDetail: "مشاهده جزئیات",
  answers: "پاسخ‌ها",
  submitAnswer: "پاسخ خود را ثبت کنید",
  writeYourAnswer: "پاسخ خود را بنویسید",
  answerPlaceholder: "متن پاسخ ...",
  answerError: "متن پاسخ نمی‌تواند خالی باشد.",
  sendAnswer: "ارسال پاسخ",
  goodAnswer: "پاسخ خوب بود",
  badAnswer: "پاسخ خوب نبود",
  username: "الناز شاکردوست",
};
